In [1]:
library ( nlme ) # Biblioteca nlme contiene los datos ’dentales ’
data ( Orthodont )
names ( Orthodont )

[1] "distance" "age"      "Subject"  "Sex"

In [5]:
# matriz de respuestas
y <- Orthodont $ distance
y <- matrix (y, ncol = 4, byrow = TRUE )
# y

In [6]:
# matrices de diseno
x <- cbind (c( rep (1 ,16) , rep (0 ,11)) , c( rep (0 ,16) , rep (1 ,11)))
z <- rbind ( rep (1 ,4) , c (8 ,10 ,12 ,14))

In [13]:
Orthodont$age

[1]  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8
 [26] 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10
 [51] 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12
 [76] 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14  8 10 12 14
[101]  8 10 12 14  8 10 12 14

In [12]:
x

[,1] [,2]
 [1,] 1    0   
 [2,] 1    0   
 [3,] 1    0   
 [4,] 1    0   
 [5,] 1    0   
 [6,] 1    0   
 [7,] 1    0   
 [8,] 1    0   
 [9,] 1    0   
[10,] 1    0   
[11,] 1    0   
[12,] 1    0   
[13,] 1    0   
[14,] 1    0   
[15,] 1    0   
[16,] 1    0   
[17,] 0    1   
[18,] 0    1   
[19,] 0    1   
[20,] 0    1   
[21,] 0    1   
[22,] 0    1   
[23,] 0    1   
[24,] 0    1   
[25,] 0    1   
[26,] 0    1   
[27,] 0    1

In [8]:
z

[,1] [,2] [,3] [,4]
[1,] 1     1    1    1  
[2,] 8    10   12   14

In [10]:
# contruye estimador para B
xx <- crossprod (x)
zz <- crossprod (t(z))
xyz <- crossprod (x, y %*% t(z))
B <- solve (xx , xyz %*% solve (zz ))
# Salida
B

[,1]     [,2]     
[1,] 16.34063 0.7843750
[2,] 17.37273 0.4795455